# Generated by Django 3.0.7 on 2020-07-06 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_students_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='name',
            field=models.CharField(db_column='names', max_length=50, null=True, unique=True),
        ),
    ]
