# Generated by Django 3.0.7 on 2020-07-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200706_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='agree',
            field=models.BooleanField(null=True),
        ),
    ]
