# Generated by Django 3.0.7 on 2020-07-06 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_students_agree'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
