# Generated by Django 3.0.7 on 2020-07-06 21:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_students_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='default',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
