# Generated by Django 3.0.7 on 2020-07-06 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_students_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='students',
            name='age',
            field=models.IntegerField(default=5, null=True),
        ),
    ]
