# Generated by Django 3.0.7 on 2020-07-06 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20200706_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
