# Generated by Django 3.0.7 on 2020-07-07 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20200707_1301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={'ordering': ['name'], 'verbose_name_plural': 'students'},
        ),
    ]
