# Generated by Django 3.0.7 on 2020-07-08 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20200707_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='date',
            new_name='created',
        ),
    ]
